### ISSUE TITLE
[PyInstaller] KeyError: 'unsupported extension: .hex'

### ISSUE THREAD

**Issue by rajanimindteck** [TexZK/hexrec#11]
Error while running "cut" command with generated exe from PyInstaller,

\hexrec\pyinstaller\win-x86>hexrec cut -s 0x04201800 -e 0x04201850 test-input.hex test-output.hex
Traceback (most recent call last):
  File "hexrec_cli.py", line 7, in <module>
  File "site-packages\hexrec-0.2.1-py3.8.egg\hexrec\__main__.py", line 43, in main
  File "site-packages\click\core.py", line 829, in __call__
  File "site-packages\click\core.py", line 782, in main
  File "site-packages\click\core.py", line 1259, in invoke
  File "site-packages\click\core.py", line 1066, in invoke
  File "site-packages\click\core.py", line 610, in invoke
  File "site-packages\hexrec-0.2.1-py3.8.egg\hexrec\cli.py", line 264, in cut
  File "site-packages\hexrec-0.2.1-py3.8.egg\hexrec\cli.py", line 110, in find_types
  File "site-packages\hexrec-0.2.1-py3.8.egg\hexrec\records.py", line 2028, in find_record_type_name
KeyError: 'unsupported extension: .hex'
[21792] Failed to execute script hexrec_cli

Even specifying input file format throws invalid choice error,

hexrec-0.2.1-py3.8.egg\hexrec\pyinstaller\win-x86>hexrec cut -s 0x04201800 -e 0x04201850 -i intel test-input.hex test-output.hex
Usage: hexrec cut [OPTIONS] INFILE OUTFILE
Try 'hexrec cut --help' for help.

Error: Invalid value for '-i' / '--input-format': invalid choice: intel. (choose from )

But, running directly from the command line tool works OK
hexrec\pyinstaller\win-x86>python -m hexrec cut -s 0x04201800 -e 0x04201850 test-input.hex test-output.hex

System environment details:
OS : Windows 10, 
Python v3.8.3

Installed hexrec from source and also tried with pip install
Same error is seen on Windows sub-system for Linux as well.

Attached input .hex file and generated hexrec.exe for reference.
[win-x86.zip](https://github.com/TexZK/hexrec/files/4798515/win-x86.zip)

**Comment by TexZK** [comment]
I can confirm that, there must be a problem with how `pyinstaller` manages entry points, because it works when launched via Python itself.

The point is `hexrec` registers file types via the `hexrec_types` list provided to `setuptools.setup(entry_points=...)`. For some reason, that list is not being read by the `hexrec` package embedded in the generated executable.

I'm not sure I'm able to fix that, or rather create some workaround.

**Comment by TexZK** [comment]
Here I found something that seems to work:
https://github.com/pyinstaller/pyinstaller/issues/3050

I will commit changes soon.

**Comment by TexZK** [comment]
@rajanimindteck: tested locally with the latest commit: https://github.com/TexZK/hexrec/commit/39e1096ecb8c7a239f200577872810b05c6d2b0f

Please confirm to close the issue.

**Comment by rajanimindteck** [comment]
PyInstaller issue is solved with this commit.

**Comment by kiesner** [comment]
@TexZK: Issue is not fixed for me even when using commit [39e1096](https://github.com/TexZK/hexrec/commit/39e1096ecb8c7a239f200577872810b05c6d2b0f).
In contrast to OP I do not try to generate an .exe for hexrec itself, but import hexrec in another module and try to package that as an executable file.

mymodule.py
```python
    import hexrec.records as hr
    ... 
```

- Create and activate a venv
- Upgrade pip
- Install hexrec and pyinstaller
- pyinstaller -y --name mymodule ./mymodule.py
- Compiled exe throws error:

```python
Traceback (most recent call last):
  File "hexdiff.py", line 163, in <module>
  File "hexdiff.py", line 153, in print_hexdiff
  File "hexdiff.py", line 124, in get_diff_list
  File "hexrec\records.py", line 569, in load_records
  File "hexrec\records.py", line 2054, in find_record_type
  File "hexrec\records.py", line 2028, in find_record_type_name
KeyError: 'unsupported extension: .s19'
[13216] Failed to execute script hexdiff
```

**Comment by TexZK** [comment]
@kiesner thanks for pointing this out. I actually have the same problem with a utility script I use at work.
In order to let *pyinstaller* compile the script into an executable file, I added the following stuff at the beginning as a workaround:

```python
from typing import MutableMapping
from typing import Type
from typing import cast

import hexrec.records as hr


# Fix missing entry_points with pyinstaller
if hasattr(sys, 'frozen') and getattr(sys, 'frozen') and hasattr(sys, '_MEIPASS'):
    import hexrec.formats.intel
    import hexrec.formats.motorola
    _record_types = cast(MutableMapping[str, Type[hr.Record]], hr.RECORD_TYPES)
    _record_types.update({
        'intel':    hexrec.formats.intel.Record,
        'motorola': hexrec.formats.motorola.Record,
    })
```

I hope to find a consistent way to make *entry points* work, otherwise I will switch back to the old solution, where I populated `hexrec.records.RECORD_TYPES` manually to their defaults, instead of relying to *entry_points*.

**Comment by TexZK** [comment]
@kiesner You can try again with the latest commit (https://github.com/TexZK/hexrec/commit/57f0e31473a9443f474e5f409aa88f07b96a46d9)
